tasks:
  - name: Setup
    before: chmod ugo+w /var/run/docker.sock && brew install buildpacks/tap/pack && pack config default-builder paketobuildpacks/builder:full && pack config trust-builder paketobuildpacks/builder:full && pack config pull-policy if-not-present
